# Generated by Django 4.1.6 on 2023-09-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
