# Generated by Django 4.2.1 on 2023-10-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_post_photo_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
