# Generated by Django 4.2.1 on 2023-11-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_profile_youtube_url_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
