# Generated by Django 4.2.1 on 2023-11-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0016_alter_category_name_alter_post_category'),
        ('theblog', '0016_alter_category_options'),
    ]

    operations = [
    ]
