# Generated by Django 4.2.1 on 2023-11-19 12:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0017_merge_20231119_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='french_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
