# Generated by Django 4.2.1 on 2023-12-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0018_post_french_body_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-post_date',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
